# Generated by Django 4.2 on 2025-04-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_client_name_for_user'),
        ),
    ]
