# Generated by Django 4.2 on 2025-04-06 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import time_tracking.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_client_unique_client_name_for_user'),
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('done', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to=time_tracking.models.invoice_upload_filepath)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_entries', to='time_tracking.invoice')),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_entries', to='time_tracking.timeentry')),
            ],
            options={
                'unique_together': {('invoice', 'time_entry')},
            },
        ),
    ]
